services:
  postgres:
    image: postgres:17-alpine
    container_name: manga-reader-postgres-dev
    environment:
      POSTGRES_DB: ${PG_MANGA_READER_DB}
      POSTGRES_USER: ${PG_MANGA_READER_USER}
      POSTGRES_PASSWORD: ${PG_MANGA_READER_PASSWORD}
    ports:
      - "127.0.0.1:${PG_PORT}:5432"
    networks:
      - manga-reader-postgres-network
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${PG_MANGA_READER_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  minio:
    image: minio/minio:latest
    container_name: manga-reader-minio-dev
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - minio-data:/data

volumes:
  pgdata:
  minio-data:

networks:
  manga-reader-postgres-network:
    driver: bridge
